// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgF7zJbZvdmYIpMzdfUKlQPtBtf2BnAvQ',
    appId: '1:488834227282:web:37013108ec7ad1b02c938b',
    messagingSenderId: '488834227282',
    projectId: 'e-commerce-343ee',
    authDomain: 'e-commerce-343ee.firebaseapp.com',
    storageBucket: 'e-commerce-343ee.firebasestorage.app',
    measurementId: 'G-M0MT89Y4DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhKJWgUQ85ECY1CqB-mtVxUibd4OhINXw',
    appId: '1:488834227282:android:006b0bd48057b5ad2c938b',
    messagingSenderId: '488834227282',
    projectId: 'e-commerce-343ee',
    storageBucket: 'e-commerce-343ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDrQIylLqdE6N12n4_ztqRkUGKs49A5YU',
    appId: '1:488834227282:ios:99f3cda5d3b1788f2c938b',
    messagingSenderId: '488834227282',
    projectId: 'e-commerce-343ee',
    storageBucket: 'e-commerce-343ee.firebasestorage.app',
    iosClientId: '488834227282-efef75nomqi51chb6ba4dbagn35pn59q.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDrQIylLqdE6N12n4_ztqRkUGKs49A5YU',
    appId: '1:488834227282:ios:99f3cda5d3b1788f2c938b',
    messagingSenderId: '488834227282',
    projectId: 'e-commerce-343ee',
    storageBucket: 'e-commerce-343ee.firebasestorage.app',
    iosClientId: '488834227282-efef75nomqi51chb6ba4dbagn35pn59q.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgF7zJbZvdmYIpMzdfUKlQPtBtf2BnAvQ',
    appId: '1:488834227282:web:c1c0624ea9fbda932c938b',
    messagingSenderId: '488834227282',
    projectId: 'e-commerce-343ee',
    authDomain: 'e-commerce-343ee.firebaseapp.com',
    storageBucket: 'e-commerce-343ee.firebasestorage.app',
    measurementId: 'G-WT18YFGTDD',
  );
}
